development:
  adapter: postgresql
  encoding: unicode
  database: image_upload_development
  pool: 50
  username: image_upload
  password: image_upload

test:
  adapter: postgresql
  encoding: unicode
  database: image_upload_test
  pool: 5
  username: image_upload
  password: image_upload
